name: md-wiki:2019

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run:  docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: Build the Docker image md-wiki:2019
      run: | 
        docker build -t ${{ secrets.DOCKER_USER }}/md-wiki:2019 .
        docker push ${{ secrets.DOCKER_USER }}/md-wiki:2019
    - name: Run a container
      run: docker run --rm -it malhar2705/md-wiki:2019
    
      
