name: md-wiki:2019

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image md-wiki:2019
      run: docker build . --file Dockerfile --tag md-wiki:2019
